// some clients can have multiple codes/representations (for historical reasons),
// so I map many to one

use std::fmt;

#[non_exhaustive]
#[derive(Debug, Copy, Clone)]
pub(crate) enum KnownClient {
    Azureus,
    Ares,
    Avicora,
    BitPump,
    Artemis,
    Vuze,
    BitBuddy,
    BitComet,
    BitFlu,
    BitLord,
    BitTorrentSDK,
    Btg,
    BitKitten,
    BitRocket,
    BTSlave,
    BitTorrent,
    BitWombat,
    BittorrentX,
    ShareazaPlus,
    EnhancedCTorrent,
    CTorrent,
    PropogateDataClient,
    Deluge,
    EBit,
    ElectricSheep,
    FileCroc,
    FlashGet,
    FreeboxBitTorrent,
    FreeDownloadManager,
    FoxTorrentRedSwoosh,
    GetRight,
    GSTorrent,
    Halite,
    Hydranode,
    KGet,
    KTorrent,
    LeechCraft,
    LhAbc,
    Linkage,
    Lphant,
    LibtorrentRasterbar,
    LibTorrentRakshasa,
    LimeWire,
    MonoTorrent,
    MooPolice,
    Miro,
    MoonlightTorrent,
    BTNextEvolution,
    NetTransport,
    OneSwarm,
    OmegaTorrent,
    CacheLogic,
    PopcornTime,
    Pando,
    PeerProject,
    PHoeniX,
    QBittorrent,
    QqDownload,
    RumTorrent,
    Retriever,
    RezTorrent,
    ShareazaAlphaBeta,
    SwiftBit,
    Xunlei,
    ShareNET,
    BitSpirit,
    PossibleBitSpirit,
    SwarmScope,
    SymTorrent,
    SharkTorrent,
    Shareaza,
    TorrentGO,
    TorrentDotNET,
    Transmission,
    TorrentStorm,
    TuoTu,
    ULeecher,
    UTorrentEmbedded,
    UTorrent,
    UTorrentMac,
    UTorrentWeb,
    WebTorrentDesktop,
    Bitlet,
    WebTorrent,
    FireTorrent,
    Vagaa,
    XanTorrent,
    MediaGet,
    Xfplay,
    XTorrent,
    ZipTorrent,
    ATorrent,
    Zona,
    InvalidPeerId,
    Abc,
    OspreyPermaseed,
    BTQueue,
    Tribler,
    Shad0w,
    BitTornado,
    UPnPNAT,
    Mainline,
    QueenBee,
    Aria,
    BitTorrentPlus,
    BitTyrantAzureusMod,
    BlizzardDownloader,
    BTugaXp,
    BtGetit,
    DeadmanWalking,
    Deadman,
    ExternalWebseed,
    G3Torrent,
    GreedBt,
    HurricaneElectric,
    HttpSeed,
    JvTorrent,
    Limewire,
    MartiniMan,
    PeerApp,
    SimpleBt,
    Swarmy,
    Teeweety,
    TorrentTopia,
    AmazonAWSS3,
    BitTorrentDna,
    Opera,
    Burst,
    TurboBt,
    BtProtocolDaemon,
    Plus,
    Xbt,
    EXeem,
    BitsOnWheels,
    MlDonkey,
    AllPeers,
    BTugaRevolution,
    Rufus,
    BitMagnet,
    Qvod,
    TopBt,
    Tixati,
    Folx,
    BiglyBt,
    BiglyBtAndroid,
}

impl fmt::Display for KnownClient {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let repr = match self {
            Self::Azureus => "Azureus",
            Self::Ares => "Ares",
            Self::Avicora => "Avicora",
            Self::BitPump => "BitPump",
            Self::Artemis => "Artemis",
            Self::Vuze => "Vuze",
            Self::BitBuddy => "BitBuddy",
            Self::BitComet => "BitComet",
            Self::BitTorrentSDK => "BitTorrent SDK",
            Self::BitFlu => "BitFlu",
            Self::BitLord => "BitLord",
            Self::Btg => "BTG",
            Self::BitKitten => "BitKitten (libtorrent)",
            Self::BitRocket => "BitRocket",
            Self::BTSlave => "BTSlave",
            Self::BitTorrent => "BitTorrent",
            Self::BitWombat => "BitWombat",
            Self::BittorrentX => "BittorrentX",
            Self::ShareazaPlus => "Shareaza Plus",
            Self::EnhancedCTorrent => "Enhanced CTorrent",
            Self::CTorrent => "CTorrent",
            Self::PropogateDataClient => "Propogate Data Client",
            Self::Deluge => "Deluge",
            Self::EBit => "EBit",
            Self::ElectricSheep => "Electric Sheep",
            Self::FileCroc => "FileCroc",
            Self::FlashGet => "FlashGet",
            Self::FreeboxBitTorrent => "Freebox BitTorrent",
            Self::FreeDownloadManager => "Free Download Manager",
            Self::FoxTorrentRedSwoosh => "FoxTorrent/RedSwoosh",
            Self::GetRight => "GetRight",
            Self::GSTorrent => "GS Torrent",
            Self::Halite => "Halite",
            Self::Hydranode => "Hydranode",
            Self::KGet => "KGet",
            Self::KTorrent => "KTorrent",
            Self::LeechCraft => "LeechCraft",
            Self::LhAbc => "LH-ABC",
            Self::Linkage => "linkage",
            Self::Lphant => "Lphant",
            Self::LibtorrentRasterbar => "libtorrent (Rasterbar)",
            // there are no known torrent clients other than rTorrent that use
            // libTorrent (Rakshasa)
            Self::LibTorrentRakshasa => "libTorrent (Rakshasa) / rTorrent",
            Self::LimeWire => "LimeWire",
            Self::MonoTorrent => "MonoTorrent",
            Self::MooPolice => "MooPolice",
            Self::Miro => "Miro",
            Self::MoonlightTorrent => "MoonlightTorrent",
            Self::BTNextEvolution => "BT Next Evolution",
            Self::NetTransport => "NetTransport",
            Self::OneSwarm => "OneSwarm",
            Self::OmegaTorrent => "OmegaTorrent",
            Self::CacheLogic => "CacheLogic",
            Self::PopcornTime => "Popcorn Time",
            Self::Pando => "Pando",
            Self::PeerProject => "PeerProject",
            Self::PHoeniX => "pHoeniX",
            Self::QBittorrent => "qBittorrent",
            Self::QqDownload => "qqdownload",
            Self::RumTorrent => "RUM Torrent",
            Self::Retriever => "Retriever",
            Self::RezTorrent => "RezTorrent",
            Self::ShareazaAlphaBeta => "Shareaza alpha/beta",
            Self::SwiftBit => "SwiftBit",
            Self::Xunlei => "\u{8FC5}\u{96F7}\u{5728}\u{7EBF} (Xunlei)",
            Self::ShareNET => "ShareNET",
            Self::BitSpirit => "BitSpirit",
            Self::PossibleBitSpirit => "BitSpirit?",
            Self::SwarmScope => "SwarmScope",
            Self::SymTorrent => "SymTorrent",
            Self::SharkTorrent => "SharkTorrent",
            Self::Shareaza => "Shareaza",
            Self::TorrentGO => "Torrent GO",
            Self::TorrentDotNET => "Torrent.NET",
            Self::Transmission => "Transmission",
            Self::TorrentStorm => "TorrentStorm",
            Self::TuoTu => "TuoTu",
            Self::ULeecher => "uLeecher!",
            Self::UTorrentEmbedded => "\u{00B5}Torrent Embedded",
            Self::UTorrent => "\u{00B5}Torrent",
            Self::UTorrentMac => "\u{00B5}Torrent Mac",
            Self::UTorrentWeb => "\u{00B5}Torrent Web",
            Self::WebTorrentDesktop => "WebTorrent Desktop",
            Self::Bitlet => "Bitlet",
            Self::WebTorrent => "WebTorrent",
            Self::FireTorrent => "FireTorrent",
            Self::Vagaa => "\u{54c7}\u{560E} (Vagaa)",
            Self::XanTorrent => "XanTorrent",
            Self::MediaGet => "MediaGet",
            Self::Xfplay => "Xfplay",
            Self::XTorrent => "XTorrent",
            Self::ZipTorrent => "ZipTorrent",
            Self::ATorrent => "aTorrent",
            Self::Zona => "Zona",
            Self::InvalidPeerId => "Invalid PeerID",
            Self::Abc => "ABC",
            Self::OspreyPermaseed => "Osprey Permaseed",
            Self::BTQueue => "BTQueue",
            Self::Tribler => "Tribler",
            Self::Shad0w => "Shad0w",
            Self::BitTornado => "BitTornado",
            Self::UPnPNAT => "UPnP NAT",
            Self::Mainline => "Mainline",
            Self::QueenBee => "Queen Bee",
            Self::Aria => "Aria",
            Self::BitTorrentPlus => "BitTorrent Plus!",
            Self::BitTyrantAzureusMod => "BitTyrant (Azureus Mod)",
            Self::BlizzardDownloader => "Blizzard Downloader",
            Self::BTugaXp => "BTugaXP",
            Self::BtGetit => "BTGetit",
            Self::DeadmanWalking => "Deadman Walking",
            Self::Deadman => "Deadman",
            Self::ExternalWebseed => "External Webseed",
            Self::G3Torrent => "G3 Torrent",
            Self::GreedBt => "GreedBT",
            Self::HurricaneElectric => "Hurricane Electric",
            Self::HttpSeed => "HTTPSeed",
            Self::JvTorrent => "JVtorrent",
            Self::Limewire => "Limewire",
            Self::MartiniMan => "Martini Man",
            Self::PeerApp => "PeerApp",
            Self::SimpleBt => "SimpleBT",
            Self::Swarmy => "Swarmy",
            Self::Teeweety => "Teeweety",
            Self::TorrentTopia => "TorrentTopia",
            Self::AmazonAWSS3 => "Amazon AWS S3",
            Self::BitTorrentDna => "BitTorrent DNA",
            Self::Opera => "Opera",
            Self::Burst => "Burst!",
            Self::TurboBt => "TurboBT",
            Self::BtProtocolDaemon => "BT Protocol Daemon",
            Self::Plus => "Plus!",
            Self::Xbt => "XBT",
            Self::EXeem => "eXeem",
            Self::BitsOnWheels => "BitsOnWheels",
            Self::MlDonkey => "MLdonkey",
            Self::AllPeers => "AllPeers",
            Self::BTugaRevolution => "BTuga Revolution",
            Self::Rufus => "Rufus",
            Self::BitMagnet => "BitMagnet",
            Self::Qvod => "QVOD",
            Self::TopBt => "Top-BT",
            Self::Tixati => "Tixati",
            Self::Folx => "folx",
            Self::BiglyBt => "BiglyBT",
            Self::BiglyBtAndroid => "BiglyBT for Android",
        };
        write!(f, "{repr}")
    }
}
